# Generated by Django 4.2.6 on 2023-12-23 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookshelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bookshelf'),
        ),
    ]
